apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentd
  namespace: fluentd
  labels:
    app: fluentd

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluentd
  labels:
    app: fluentd
rules:
  - apiGroups:
    - ""
    resources:
      - pods
      - namespaces
    verbs:
      - get
      - list
      - watch

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fluentd
roleRef:
  kind: ClusterRole
  name: fluentd
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: fluentd
  namespace: fluentd

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: fluentd
data:
  fluent.conf: |
    @include pods-fluent.conf
    @include elastic-fluent.conf

  pods-fluent.conf: |-
    <source>
      @type tail
      #@log_level info
      read_from_head true
      tag kubernetes.*
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.log.pos
      exclude_path ["/var/log/containers/fluent*", "/var/log/containers/kube-*", "/var/log/containers/etcd-*", "/var/log/containers/coredns-*", "/var/log/containers/cilium-*", "/var/log/containers/*elasticsearch*","/var/log/containers/kibana*"]
      <parse>
        @type cri
      </parse>
    </source>

    <filter **>
      @type record_transformer
      <record>
        application_uuid "10923aldklakjd-adlkna-3"
      </record>
    </filter>

    <filter kubernetes.**>
      @type kubernetes_metadata
      @id filter_kube_metadata
      kubernetes_url "#{ENV['FLUENT_FILTER_KUBERNETES_URL'] || 'https://' + ENV.fetch('KUBERNETES_SERVICE_HOST') + ':' + ENV.fetch('KUBERNETES_SERVICE_PORT') + '/api'}"
      verify_ssl "#{ENV['KUBERNETES_VERIFY_SSL'] || true}"
      ca_file "#{ENV['KUBERNETES_CA_FILE']}"
      skip_labels "#{ENV['FLUENT_KUBERNETES_METADATA_SKIP_LABELS'] || 'false'}"
      skip_container_metadata "#{ENV['FLUENT_KUBERNETES_METADATA_SKIP_CONTAINER_METADATA'] || 'false'}"
      skip_master_url "#{ENV['FLUENT_KUBERNETES_METADATA_SKIP_MASTER_URL'] || 'false'}"
      skip_namespace_metadata "#{ENV['FLUENT_KUBERNETES_METADATA_SKIP_NAMESPACE_METADATA'] || 'false'}"
    </filter>

  elastic-fluent.conf: |-
    #<match **>
    <match kubernetes.**>
      @type elasticsearch
      @log_level info
      host "#{ENV['FLUENT_ELASTICSEARCH_HOST']}"
      port "#{ENV['FLUENT_ELASTICSEARCH_PORT']}"
      user "#{ENV['FLUENT_ELASTICSEARCH_USER']}"
      password "#{ENV['FLUENT_ELASTICSEARCH_PASSWORD']}"
      scheme "#{ENV['FLUENT_ELASTICSEARCH_SCHEME'] || 'http'}"
      ssl_verify "#{ENV['FLUENT_ELASTICSEARCH_SSL_VERIFY'] || 'true'}"
      index_name "fluentd-k8s-poc-%Y.%m.%d"
      type_name fluentd
      include_timestamp true
    </match>

  K8S_NODE_NAME: "efk-stack"
  FLUENT_ELASTICSEARCH_USER: "elastic"
  NUMBER_OF_REPLICAS: "2"
  FLUENT_ELASTICSEARCH_HOST: "elasticsearch.elasticsearch.svc.cluster.local"
---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: fluentd
  labels:
    app: fluentd
spec:
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      serviceAccount: fluentd
      serviceAccountName: fluentd
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: fluentd
        image: fluent/fluentd-kubernetes-daemonset:v1.16-debian-elasticsearch7-2
        env:
          - name: FLUENT_ELASTICSEARCH_HOST
            valueFrom:
              configMapKeyRef:
                name: fluentd-config
                key: FLUENT_ELASTICSEARCH_HOST
          - name: FLUENT_ELASTICSEARCH_PORT
            value: "9200"
          - name: FLUENT_ELASTICSEARCH_SCHEME
            value: "http"
          - name: FLUENTD_SYSTEMD_CONF
            value: disable
          - name: K8S_NODE_NAME
            valueFrom:
              configMapKeyRef:
                name: fluentd-config
                key: K8S_NODE_NAME
          - name: FLUENT_ELASTICSEARCH_USER
            valueFrom:
              configMapKeyRef:
                name: fluentd-config
                key: FLUENT_ELASTICSEARCH_USER
          - name: FLUENT_ELASTICSEARCH_PASSWORD
            valueFrom:
              secretKeyRef:
                name: elastic-credentials
                key: ELASTIC_PASSWORD
#          - name: FLUENT_UID
#            value: "0"
#          - name: FLUENT_CONTAINER_TAIL_EXCLUDE_PATH
#            value: /var/log/containers/fluent*
#          - name: FLUENT_CONTAINER_TAIL_PARSER_TYPE
#            value: /^(?<time>.+) (?<stream>stdout|stderr) [^ ]* (?<log>.*)$/
#          - name: FLUENT_ELASTICSEARCH_SED_DISABLE
#            value: "true"
        resources:
          limits:
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: fluentd-config
          mountPath: /fluentd/etc
        - name: varlog
          mountPath: /var/log
        - name: varlogcontainers
          mountPath: /var/log/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlogcontainers
        hostPath:
          path: /var/log/containers
      - name: fluentd-config
        configMap:
          name: fluentd-config
